# Generated by Django 4.1.6 on 2023-02-06 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chrab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=400)),
                ('glass', models.CharField(max_length=400)),
                ('first_ingredient', models.CharField(max_length=400, null=True)),
                ('second_ingredient', models.CharField(max_length=400, null=True)),
                ('third_ingredient', models.CharField(max_length=400, null=True)),
                ('fourth_ingredient', models.CharField(max_length=400, null=True)),
                ('instructions', models.CharField(max_length=1000)),
                ('drink_image', models.CharField(max_length=400)),
                ('first_ingredient_measurements', models.CharField(max_length=400, null=True)),
                ('second_ingredient_measurements', models.CharField(max_length=400, null=True)),
                ('third_ingredient_measurements', models.CharField(max_length=400, null=True)),
                ('fourth_ingredient_measurements', models.CharField(max_length=400, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
